# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT

# Installs JAVA 1.7 in VM
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
echo "oracle-java7-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
sudo apt-get install -y oracle-java7-installer


# Auto login on startup for this VM
sudo mkdir /etc/lightdm/lightdm.conf.d
sudo touch /etc/lightdm/lightdm.conf.d/50-myconfig.conf
sudo echo "[SeatDefaults]" >> /etc/lightdm/lightdm.conf.d/50-myconfig.conf
sudo echo "autologin-user=vagrant" >> /etc/lightdm/lightdm.conf.d/50-myconfig.conf


# Create 'Desktop' directory and change directory to 'Desktop' (this is where files are stored)
mkdir Desktop
cd Desktop


# Disable screen lockout for this VM
cd ..
sudo touch login_desktop.sh
sudo echo "#! /bin/bash" >> login_desktop.sh
sudo echo "/usr/bin/gsettings set org.gnome.desktop.screensaver lock-enabled false" >> login_desktop.sh
sudo chmod +x login_desktop.sh

sudo touch login_desktop.sh.desktop
sudo echo "[Desktop Entry]" >> login_desktop.sh.desktop
sudo echo "Type=Application" >> login_desktop.sh.desktop
sudo echo "Exec=/home/vagrant/login_desktop.sh" >> login_desktop.sh.desktop
sudo echo "Hidden=false" >> login_desktop.sh.desktop
sudo echo "NoDisplay=false" >> login_desktop.sh.desktop
sudo echo "X-GNOME-Autostart-enabled=true" >> login_desktop.sh.desktop
sudo echo "Name=LockScreen Disabled" >> login_desktop.sh.desktop
sudo echo "Comment=Disable the lock screen" >> login_desktop.sh.desktop
sudo chmod +x /home/vagrant/login_desktop.sh.desktop
sudo update-desktop-database

sudo cp login_desktop.sh.desktop /etc/xdg/autostart/login_desktop.sh.desktop


# Install Eclipse and workspace (to run the tool)
cd /home/vagrant/Desktop
sudo wget -O /home/vagrant/Desktop/eclipse.tar.gz "https://googledrive.com/host/0B5qzMDCI2DFJaV9Sek9sZDUzdjA/eclipse.tar.gz"
tar xvzf eclipse.tar.gz
rm -f eclipse.tar.gz
# sudo chmod 777 -R /home/vagrant/Desktop/*
sudo ln -s eclipse/eclipse /usr/bin/eclipse


# Create an application launcher for Eclipse (to launch it on startup)
sudo touch /usr/share/applications/eclipse.desktop
sudo echo "[Desktop Entry]" >> /usr/share/applications/eclipse.desktop
sudo echo "Version=4.4" >> /usr/share/applications/eclipse.desktop
sudo echo "Name=Eclipse" >> /usr/share/applications/eclipse.desktop
sudo echo "Comment=Integrated Development Environment" >> /usr/share/applications/eclipse.desktop
sudo echo "Exec=/home/vagrant/Desktop/eclipse/eclipse -clean -data /home/vagrant/Desktop/workspace -vm /usr/lib/jvm/java-7-oracle/bin/java" >> /usr/share/applications/eclipse.desktop
sudo echo "Type=Application" >> /usr/share/applications/eclipse.desktop
sudo echo "Icon=/opt/eclipse/icon.xpm" >> /usr/share/applications/eclipse.desktop
sudo echo "Terminal=false" >> /usr/share/applications/eclipse.desktop
sudo echo "NoDisplay=false" >> /usr/share/applications/eclipse.desktop
sudo echo "Categories=Development;IDE" >> /usr/share/applications/eclipse.desktop
sudo chmod +x /usr/share/applications/eclipse.desktop
sudo update-desktop-database


# Obtain required Desktop files for VM
sudo wget -O /home/vagrant/Desktop/vm-files.tar.gz "https://github.com/SoftwareEngineeringToolDemos/ICSE-2014-Atlas/raw/master/build-vm/vm-files.tar.gz"
tar zxvf /home/vagrant/Desktop/vm-files.tar.gz -C /home/vagrant/Desktop/
sudo rm /home/vagrant/Desktop/vm-files.tar.gz
pwd


# Install Atlas plugin in Eclipse (Configuring tool)
cd eclipse
./eclipse -application org.eclipse.equinox.p2.director -repository http://download.ensoftcorp.com/atlas/eclipse -installIU com.ensoftcorp.atlas.java.feature.feature.group


# Start Eclipse on startup (Add Eclipse to startup)
cd /home/vagrant/.config/
mkdir autostart
sudo cp /usr/share/applications/eclipse.desktop /home/vagrant/.config/autostart/


# Remove unused icons from sidebar (making VM as minimal as possible)
sudo rm -f "/usr/share/applications/ubuntu-amazon-default.desktop"
sudo rm -f "/usr/share/applications/libreoffice-calc.desktop"
sudo rm -f "/usr/share/applications/libreoffice-writer.desktop"
sudo rm -f "/usr/share/applications/libreoffice-impress.desktop"
sudo rm -f "/usr/share/applications/ubuntu-software-center.desktop"


# Open README.txt and License.txt on startup (helps in configuring and using tool)
cd /home/vagrant
sudo touch start_gedit.sh
sudo echo "#! /bin/bash" >> start_gedit.sh
sudo echo "gedit /home/vagrant/Desktop/README.txt /home/vagrant/Desktop/License.txt" >> start_gedit.sh
sudo chmod +x start_gedit.sh

sudo touch start_gedit.sh.desktop
sudo echo "[Desktop Entry]" >> start_gedit.sh.desktop
sudo echo "Type=Application" >> start_gedit.sh.desktop
sudo echo "Exec=/home/vagrant/start_gedit.sh" >> start_gedit.sh.desktop
sudo echo "Hidden=false" >> start_gedit.sh.desktop
sudo echo "NoDisplay=false" >> start_gedit.sh.desktop
sudo echo "X-GNOME-Autostart-enabled=true" >> start_gedit.sh.desktop
sudo echo "Name=LockScreen Disabled" >> start_gedit.sh.desktop
sudo echo "Comment=Disable the lock screen" >> start_gedit.sh.desktop
sudo chmod +x /home/vagrant/start_gedit.sh.desktop
sudo update-desktop-database

sudo cp start_gedit.sh.desktop /home/vagrant/.config/autostart/start_gedit.sh.desktop


# Final update command
sudo apt-get update


# Reboot machine, for all changes to be applied
sudo reboot

SCRIPT

Vagrant.configure(2) do |config|
  # Configuring box to be used to create VM
  config.vm.box = "box-cutter/ubuntu1404-desktop"

  # Configuring VM provider to be used to host this VM
  config.vm.provider "virtualbox" do |vb|
    # To get UI
    vb.gui = true
    # Configuring name of the VM
    vb.name = "ICSE-2014-Atlas"
    # Configuring memory to be used for this VM
    vb.memory = "2048"
    # Configuring cpus to be used for this VM
    vb.cpus = 2
  end

  # Configuring shell provisioner
  config.vm.provision "shell" do |s|
    # Running script through shell
    s.inline = $script
  end
end
